// Bundled hadith — currently just Nawawi 40 (fawazahmed0, Unlicense), so hadith
// resolves offline on a fresh install. The JSON is generated by
// scripts/gen-nawawi40.mjs to match normalizeFawaz output. Not unit-testable as
// "logic" — a load test validates the shipped data.

import nawawi40 from "./data/nawawi40.json";
import type { HadithCollection } from "./schema";

const BUNDLED: HadithCollection[] = [nawawi40 as HadithCollection];

export class HadithCoreLoader {
	listCollections(): HadithCollection[] {
		return BUNDLED;
	}
	get(collection: string): HadithCollection | undefined {
		return BUNDLED.find((c) => c.collection === collection);
	}
}
